# Generated by Django 5.2.4 on 2026-02-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_slug_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE app_product SET slug = 'temp-' || id WHERE slug IS NULL OR slug = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
