# Generated by Django 5.2.4 on 2026-02-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='appearance',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_traceability',
            field=models.TextField(blank=True, default='', verbose_name='Batch Traceability Info'),
        ),
        migrations.AddField(
            model_name='product',
            name='boiling_point',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='cas_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='CAS Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='common_names',
            field=models.TextField(blank=True, default='', help_text='Synonyms – one per line', verbose_name='Common Name / Synonyms'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_materials',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_support_contact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='dangerous_goods',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Dangerous Goods'),
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='disposal_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_point',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description shown on the product detail page'),
        ),
        migrations.AddField(
            model_name='product',
            name='ghs_classification',
            field=models.TextField(blank=True, default='', verbose_name='GHS Hazard Classification'),
        ),
        migrations.AddField(
            model_name='product',
            name='gross_weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='handling_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='hazard_pictograms',
            field=models.CharField(blank=True, default='', help_text='GHS pictogram codes separated by commas, e.g. "GHS02, GHS07"', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='hazard_statements',
            field=models.TextField(blank=True, default='', help_text='H-codes – one per line'),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='HS Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='industry_usage',
            field=models.TextField(blank=True, default='', help_text='e.g. Pharma, Textile, Paint, Agriculture …'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_analytical_grade',
            field=models.BooleanField(default=False, verbose_name='Analytical Grade'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_industrial_grade',
            field=models.BooleanField(default=False, verbose_name='Industrial Grade'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pharma_grade',
            field=models.BooleanField(default=False, verbose_name='Pharma Grade'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_technical_grade',
            field=models.BooleanField(default=False, verbose_name='Technical Grade'),
        ),
        migrations.AddField(
            model_name='product',
            name='iso_certification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='melting_point',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='molecular_formula',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='molecular_weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Minimum Order Quantity (MOQ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='odor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_sizes',
            field=models.TextField(blank=True, default='', help_text='Available pack sizes – one per line'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, default='', help_text='Drum, Bottle, Bag, Tanker, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ph_value',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='product',
            name='precautionary_statements',
            field=models.TextField(blank=True, default='', help_text='P-codes – one per line'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_applications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='purity_grade',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Purity / Grade'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_dosage',
            field=models.TextField(blank=True, default='', verbose_name='Recommended Dosage / Usage Rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='refractive_index',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='regulatory_compliance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sds_file',
            field=models.FileField(blank=True, null=True, upload_to='products/sds/', verbose_name='Safety Data Sheet (SDS)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_restrictions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='signal_word',
            field=models.CharField(blank=True, choices=[('', '— Not set —'), ('Danger', 'Danger'), ('Warning', 'Warning')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SKU / Product Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='solubility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='stability_reactivity',
            field=models.TextField(blank=True, default='', verbose_name='Stability / Reactivity'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='structure_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/structures/', verbose_name='Structure Formula Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='transport_class',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='un_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='UN Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='vapor_pressure',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='viscosity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Short description shown on product cards'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Short symbol for the icon circle, e.g. "H2S"', max_length=10),
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('COA', 'Certificate of Analysis'), ('TDS', 'Technical Data Sheet'), ('SDS', 'Safety Data Sheet (SDS)'), ('MSDS', 'Material Safety Data Sheet (MSDS)'), ('ISO', 'ISO Certificate'), ('GMP', 'GMP Certificate'), ('HALAL', 'Halal Certificate'), ('KOSHER', 'Kosher Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='products/documents/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.product')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Show this image as the main product image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.CharField(max_length=100)),
                ('max_quantity', models.CharField(blank=True, default='', max_length=100)),
                ('price_info', models.CharField(help_text='Descriptive (e.g. "Contact for pricing", "₹120/kg")', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='app.product')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'ordering': ['order'],
            },
        ),
    ]
