# Generated by Django 5.2.4 on 2026-02-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_appearance_product_batch_traceability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_name',
        ),
    ]
