# Generated by Django 5.2.4 on 2026-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_manufacturer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Vasudev Chemo Pharma', max_length=200)),
                ('company_logo', models.ImageField(blank=True, help_text='Primary company logo (used in header, footer, etc.)', null=True, upload_to='company/')),
                ('company_name_image', models.ImageField(blank=True, help_text='Company name as an image / wordmark', null=True, upload_to='company/')),
                ('tagline', models.CharField(blank=True, default='', help_text='Short tagline / slogan', max_length=300)),
                ('about_short', models.TextField(blank=True, default='', help_text='Short description (shown in footer, etc.)')),
                ('phone_primary', models.CharField(blank=True, default='', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, default='', help_text='Sales team / alternate number', max_length=30)),
                ('phone_export', models.CharField(blank=True, default='', help_text='Export enquiry phone number', max_length=30)),
                ('email_general', models.EmailField(blank=True, default='', max_length=254)),
                ('email_sales', models.EmailField(blank=True, default='', max_length=254)),
                ('email_export', models.EmailField(blank=True, default='', max_length=254)),
                ('email_support', models.EmailField(blank=True, default='', max_length=254)),
                ('address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('gst_number', models.CharField(blank=True, default='', max_length=50, verbose_name='GST Number')),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('cin_number', models.CharField(blank=True, default='', help_text='Company Identification Number', max_length=50, verbose_name='CIN Number')),
                ('iec_code', models.CharField(blank=True, default='', help_text='Import Export Code', max_length=30, verbose_name='IEC Code')),
                ('website_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=30)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('google_maps_embed', models.TextField(blank=True, default='', help_text='Google Maps embed iframe HTML or link')),
            ],
            options={
                'verbose_name': 'Company Details',
                'verbose_name_plural': 'Company Details',
            },
        ),
    ]
