# Generated by Django 5.2.4 on 2026-02-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='google_maps_embed',
            field=models.URLField(blank=True, default='', help_text='Google Maps embed URL only (e.g. https://www.google.com/maps/embed?pb=…). Do NOT paste full iframe HTML.', max_length=1000),
        ),
    ]
