# Generated by Django 5.2.4 on 2026-02-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_google_maps_embed_to_urlfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description_seo',
            field=models.TextField(blank=True, default='', help_text='Custom meta description for search engines. Leave blank to use short description.', verbose_name='SEO Meta Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', help_text='Comma-separated keywords for meta tags and SEO.', verbose_name='Meta Keywords / Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_h1',
            field=models.CharField(blank=True, default='', help_text='Custom H1 heading for the product page. Leave blank to use product name.', max_length=300, verbose_name='SEO H1 Heading'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_h2_tags',
            field=models.TextField(blank=True, default='', help_text='One per line. Rendered as hidden H2 headings on the page for SEO.', verbose_name='SEO H2 Sub-headings'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_rich_text',
            field=models.TextField(blank=True, default='', help_text='Keyword-rich content block rendered on the product page (below overview) for Google indexing.', verbose_name='SEO Rich Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Custom page <title> for search engines. Leave blank to use product name.', max_length=300, verbose_name='SEO Page Title'),
        ),
    ]
