# Generated by Django 5.2.4 on 2026-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_seo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('short_summary', models.TextField(blank=True, default='', help_text='Short intro shown in article cards and below the title.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('content', models.TextField(help_text='Main article body. Use blank lines to split paragraphs.')),
                ('key_highlights', models.TextField(blank=True, default='', help_text='One highlight per line (shown as key points).')),
                ('is_published', models.BooleanField(default=False)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, default='', max_length=300)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='', help_text='Comma-separated keywords.')),
                ('contact_section_title', models.CharField(blank=True, default='Need Product Support?', max_length=180)),
                ('contact_section_text', models.TextField(blank=True, default='')),
                ('contact_person', models.CharField(blank=True, default='', max_length=150)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_cta_text', models.CharField(blank=True, default='Contact Us', max_length=80)),
                ('contact_cta_url', models.CharField(blank=True, default='/products', max_length=300)),
                ('promote_section_title', models.CharField(blank=True, default='Explore Our Other Products', max_length=180)),
                ('promote_section_text', models.TextField(blank=True, default='')),
                ('promoted_products', models.ManyToManyField(blank=True, related_name='article_promotions', to='app.product')),
            ],
            options={
                'verbose_name': 'Product Article',
                'verbose_name_plural': 'Product Articles',
                'ordering': ['-published_on', 'order', '-id'],
            },
        ),
    ]
